
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
required = [
  "github.com/magefile/mage/mage",
]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "v1.13.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.13.57"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.0"

[[override]]
  name = "github.com/mitchellh/go-ps"
  version = "v1.0.0"

[[override]]
  name = "github.com/go-ini/ini"
  version = "v1.28.2"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v16"

[[constraint]]
  branch = "master"
  name = "github.com/gravitational/configure"

[[constraint]]
  version = "1.0.0"
  name = "github.com/gravitational/roundtrip"

[[constraint]]
  version = "=1.1.10"
  name = "github.com/gravitational/trace"

[[constraint]]
  name = "github.com/gravitational/version"
  version = "0.0.1"

[[constraint]]
  name = "github.com/hashicorp/serf"
  version = "0.8.1"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = ">=0.10.0, <=403.0.0-gf18d7e7"

[[constraint]]
  name = "github.com/jonboulle/clockwork"
  revision = "62fb9bc030d14f92c58df3c1601e50a0e445edef"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/prometheus/procfs"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  source = "github.com/gravitational/logrus"
  version = "v1.4.3-alpha.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "release-branch.go1.9"

[[constraint]]
  name = "google.golang.org/grpc"
  version = ">=v1.5.2"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.1.11"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/gosigar"

[[override]]
  name = "github.com/json-iterator/go"
  version = "=1.1.5"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/hdrhistogram"

[[constraint]]
  version = "0.0.1"
  name = "github.com/gravitational/ttlmap"
